steps:
  - name: "gcr.io/cloud-builders/gcloud"  # Use the gcloud build image
    args:
      - "functions"
      - "deploy"
      - "openUrl"  # Replace with your Cloud Function name
      - "--runtime=nodejs16"  # Specify the runtime
      - "--trigger-topic=your-topic-name"  # The Pub/Sub topic to trigger the function
      - "--entry-point=openUrlurl-open-topic"  # The function's entry point
      - "--allow-unauthenticated"  # Allow public access if needed

timeout: "900s"  # Build timeout in seconds
